// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudflare.Zones.Item.Logpush.Validate.Destination;
using Soenneker.Cloudflare.Zones.Item.Logpush.Validate.Origin;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudflare.Zones.Item.Logpush.Validate
{
    /// <summary>
    /// Builds and executes requests for operations under \zones\{identifier-id}\logpush\validate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ValidateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The destination property</summary>
        public global::Soenneker.Cloudflare.Zones.Item.Logpush.Validate.Destination.DestinationRequestBuilder Destination
        {
            get => new global::Soenneker.Cloudflare.Zones.Item.Logpush.Validate.Destination.DestinationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The origin property</summary>
        public global::Soenneker.Cloudflare.Zones.Item.Logpush.Validate.Origin.OriginRequestBuilder Origin
        {
            get => new global::Soenneker.Cloudflare.Zones.Item.Logpush.Validate.Origin.OriginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.Zones.Item.Logpush.Validate.ValidateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/{identifier%2Did}/logpush/validate", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.Zones.Item.Logpush.Validate.ValidateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/{identifier%2Did}/logpush/validate", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
