// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Available_alerts;
using Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Destinations;
using Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.History;
using Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Policies;
using Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Silences;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3
{
    /// <summary>
    /// Builds and executes requests for operations under \accounts\{account_identifier-id}\alerting\v3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V3RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The available_alerts property</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Available_alerts.Available_alertsRequestBuilder Available_alerts
        {
            get => new global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Available_alerts.Available_alertsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The destinations property</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Destinations.DestinationsRequestBuilder Destinations
        {
            get => new global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Destinations.DestinationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The history property</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.History.HistoryRequestBuilder History
        {
            get => new global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.History.HistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The policies property</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Policies.PoliciesRequestBuilder Policies
        {
            get => new global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Policies.PoliciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The silences property</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Silences.SilencesRequestBuilder Silences
        {
            get => new global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.Silences.SilencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_identifier%2Did}/alerting/v3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Accounts.Item.Alerting.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/accounts/{account_identifier%2Did}/alerting/v3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
