// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudflare.OpenApiClient.Zones.Item.Dcv_delegation.Uuid;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Zones.Item.Dcv_delegation
{
    /// <summary>
    /// Builds and executes requests for operations under \zones\{identifier-id}\dcv_delegation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Dcv_delegationRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The uuid property</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Zones.Item.Dcv_delegation.Uuid.UuidRequestBuilder Uuid
        {
            get => new global::Soenneker.Cloudflare.OpenApiClient.Zones.Item.Dcv_delegation.Uuid.UuidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Zones.Item.Dcv_delegation.Dcv_delegationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Dcv_delegationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/{identifier%2Did}/dcv_delegation", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Zones.Item.Dcv_delegation.Dcv_delegationRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Dcv_delegationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/zones/{identifier%2Did}/dcv_delegation", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
