// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.Bot_class;
using Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.Compromised;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary
{
    /// <summary>
    /// Builds and executes requests for operations under \radar\leaked_credential_checks\summary
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SummaryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bot_class property</summary>
        public global::Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.Bot_class.Bot_classRequestBuilder Bot_class
        {
            get => new global::Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.Bot_class.Bot_classRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compromised property</summary>
        public global::Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.Compromised.CompromisedRequestBuilder Compromised
        {
            get => new global::Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.Compromised.CompromisedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.SummaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SummaryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/leaked_credential_checks/summary", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.Radar.Leaked_credential_checks.Summary.SummaryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SummaryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/radar/leaked_credential_checks/summary", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
