// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>
    /// Settings for application observability such as logging.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CcApplicationObservability : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Observability logging settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.CcObservabilityLogs? Logs { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.CcObservabilityLogs Logs { get; set; }
#endif
        /// <summary>Fixed number of instances that should receive the application-level observability overlay.Mutually exclusive with `target_instance_percentage`.</summary>
        public int? TargetInstanceCount { get; set; }
        /// <summary>Percentage of instances that should receive the application-level observability overlay.This rounds up so at least this percentage of instances is targeted.Mutually exclusive with `target_instance_count`.</summary>
        public int? TargetInstancePercentage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.CcApplicationObservability"/> and sets the default values.
        /// </summary>
        public CcApplicationObservability()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.CcApplicationObservability"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.CcApplicationObservability CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.OpenApiClient.Models.CcApplicationObservability();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "logs", n => { Logs = n.GetObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.CcObservabilityLogs>(global::Soenneker.Cloudflare.OpenApiClient.Models.CcObservabilityLogs.CreateFromDiscriminatorValue); } },
                { "target_instance_count", n => { TargetInstanceCount = n.GetIntValue(); } },
                { "target_instance_percentage", n => { TargetInstancePercentage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.CcObservabilityLogs>("logs", Logs);
            writer.WriteIntValue("target_instance_count", TargetInstanceCount);
            writer.WriteIntValue("target_instance_percentage", TargetInstancePercentage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
