// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomIndicatorFeedsIndicatorFeedMetadata : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date and time when the data entry was created</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The description of the example test</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The unique identifier for the indicator feed</summary>
        public int? Id { get; set; }
        /// <summary>Whether the indicator feed can be attributed to a provider</summary>
        public bool? IsAttributable { get; set; }
        /// <summary>Whether the indicator feed can be downloaded</summary>
        public bool? IsDownloadable { get; set; }
        /// <summary>Whether the indicator feed is exposed to customers</summary>
        public bool? IsPublic { get; set; }
        /// <summary>Summary of indicator counts from the last successful upload to thisfeed. Populated by the custom-threat-feeds loader at the end of eachsuccessful load. Absent (omitted) when no upload has completedsuccessfully or the upload errored before the summary write.Surfaces silent-failure paths so operators can see when theirindicators were dropped (popularity allowlist, expired valid_until,etc.) without reading loader logs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsLastUploadSummary? LastUploadSummary { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsLastUploadSummary LastUploadSummary { get; set; }
#endif
        /// <summary>Human-readable error message describing why the latest uploadfailed. Populated only when `latest_upload_status` is `Error`.Returns one of a small fixed set of category-level messages(invalid domain / IP / URL entries, malformed row or header,invalid valid_until timestamp, etc.) or the generic`Upload failed` for unknown or infrastructure-level errors.Never echoes raw error text from the underlying loader.Intel accounts receive the verbatim loader/API error text(including specific offending values) instead of thesecategory-level messages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestUploadError { get; set; }
#nullable restore
#else
        public string LatestUploadError { get; set; }
#endif
        /// <summary>Status of the latest snapshot uploaded</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata_latest_upload_status? LatestUploadStatus { get; set; }
        /// <summary>The date and time when the data entry was last modified</summary>
        public DateTimeOffset? ModifiedOn { get; set; }
        /// <summary>The name of the indicator feed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The unique identifier for the provider</summary>
        public int? ProviderId { get; set; }
        /// <summary>The provider of the indicator feed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderName { get; set; }
#nullable restore
#else
        public string ProviderName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata"/> and sets the default values.
        /// </summary>
        public CustomIndicatorFeedsIndicatorFeedMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_on", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_attributable", n => { IsAttributable = n.GetBoolValue(); } },
                { "is_downloadable", n => { IsDownloadable = n.GetBoolValue(); } },
                { "is_public", n => { IsPublic = n.GetBoolValue(); } },
                { "last_upload_summary", n => { LastUploadSummary = n.GetObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsLastUploadSummary>(global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsLastUploadSummary.CreateFromDiscriminatorValue); } },
                { "latest_upload_error", n => { LatestUploadError = n.GetStringValue(); } },
                { "latest_upload_status", n => { LatestUploadStatus = n.GetEnumValue<global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata_latest_upload_status>(); } },
                { "modified_on", n => { ModifiedOn = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "provider_id", n => { ProviderId = n.GetIntValue(); } },
                { "provider_name", n => { ProviderName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_on", CreatedOn);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_attributable", IsAttributable);
            writer.WriteBoolValue("is_downloadable", IsDownloadable);
            writer.WriteBoolValue("is_public", IsPublic);
            writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsLastUploadSummary>("last_upload_summary", LastUploadSummary);
            writer.WriteStringValue("latest_upload_error", LatestUploadError);
            writer.WriteEnumValue<global::Soenneker.Cloudflare.OpenApiClient.Models.CustomIndicatorFeedsIndicatorFeedMetadata_latest_upload_status>("latest_upload_status", LatestUploadStatus);
            writer.WriteDateTimeOffsetValue("modified_on", ModifiedOn);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("provider_id", ProviderId);
            writer.WriteStringValue("provider_name", ProviderName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
