// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Dlp_EmailRuleSelector
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Recipients")]
        #pragma warning disable CS1591
        Recipients,
        #pragma warning restore CS1591
        [EnumMember(Value = "Sender")]
        #pragma warning disable CS1591
        Sender,
        #pragma warning restore CS1591
        [EnumMember(Value = "DLPProfiles")]
        #pragma warning disable CS1591
        DLPProfiles,
        #pragma warning restore CS1591
    }
}
