// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FraudFraudSettings : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Configuration for classifying login authentication outcomes based on the origin response.Requires `user_profiles` to be enabled.- Success and failure criteria are independently updatable — sending only `success_criteria`  leaves failure codes untouched, and vice versa.- Omit `authentication_settings` entirely to leave both unchanged.- Status codes must not overlap between success and failure criteria.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.FraudAuthenticationSettings? AuthenticationSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.FraudAuthenticationSettings AuthenticationSettings { get; set; }
#endif
        /// <summary>List of expressions to detect usernames in write HTTP requests.- Maximum of 10 expressions.- Omit or set to null to leave unchanged on update.- Provide an empty array `[]` to clear all expressions on update.- Invalid expressions will result in a 10400 Bad Request with details in the `messages` array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UsernameExpressions { get; set; }
#nullable restore
#else
        public List<string> UsernameExpressions { get; set; }
#endif
        /// <summary>Whether Fraud User Profiles is enabled for the zone.</summary>
        public global::Soenneker.Cloudflare.OpenApiClient.Models.FraudUserProfilesStatus? UserProfiles { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.FraudFraudSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.FraudFraudSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.OpenApiClient.Models.FraudFraudSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authentication_settings", n => { AuthenticationSettings = n.GetObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.FraudAuthenticationSettings>(global::Soenneker.Cloudflare.OpenApiClient.Models.FraudAuthenticationSettings.CreateFromDiscriminatorValue); } },
                { "user_profiles", n => { UserProfiles = n.GetEnumValue<global::Soenneker.Cloudflare.OpenApiClient.Models.FraudUserProfilesStatus>(); } },
                { "username_expressions", n => { UsernameExpressions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.FraudAuthenticationSettings>("authentication_settings", AuthenticationSettings);
            writer.WriteCollectionOfPrimitiveValues<string>("username_expressions", UsernameExpressions);
            writer.WriteEnumValue<global::Soenneker.Cloudflare.OpenApiClient.Models.FraudUserProfilesStatus>("user_profiles", UserProfiles);
        }
    }
}
#pragma warning restore CS0618
