// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IntelUrlIntelligence : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Content categories associated with this URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource>? ContentCategories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource> ContentCategories { get; set; }
#endif
        /// <summary>The full URL that was looked up.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullUrl { get; set; }
#nullable restore
#else
        public string FullUrl { get; set; }
#endif
        /// <summary>The hostname of the URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hostname { get; set; }
#nullable restore
#else
        public string Hostname { get; set; }
#endif
        /// <summary>Security risk types associated with this URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource>? RiskType { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource> RiskType { get; set; }
#endif
        /// <summary>The path component of the URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UrlPath { get; set; }
#nullable restore
#else
        public string UrlPath { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligence"/> and sets the default values.
        /// </summary>
        public IntelUrlIntelligence()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligence"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligence CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content_categories", n => { ContentCategories = n.GetCollectionOfObjectValues<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource>(global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "full_url", n => { FullUrl = n.GetStringValue(); } },
                { "hostname", n => { Hostname = n.GetStringValue(); } },
                { "risk_type", n => { RiskType = n.GetCollectionOfObjectValues<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource>(global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "url_path", n => { UrlPath = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource>("content_categories", ContentCategories);
            writer.WriteStringValue("full_url", FullUrl);
            writer.WriteStringValue("hostname", Hostname);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Cloudflare.OpenApiClient.Models.IntelUrlIntelligenceCategoryWithSource>("risk_type", RiskType);
            writer.WriteStringValue("url_path", UrlPath);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
