// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>&quot;Tunnel type: gre, ipsec, or cni&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MagicRedundancyMemberRequest_type
    {
        [EnumMember(Value = "gre")]
        #pragma warning disable CS1591
        Gre,
        #pragma warning restore CS1591
        [EnumMember(Value = "ipsec")]
        #pragma warning disable CS1591
        Ipsec,
        #pragma warning restore CS1591
        [EnumMember(Value = "cni")]
        #pragma warning disable CS1591
        Cni,
        #pragma warning restore CS1591
    }
}
