// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Mcn_onramp_lifecycle_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OnrampNeedsApply")]
        #pragma warning disable CS1591
        OnrampNeedsApply,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampPendingPlan")]
        #pragma warning disable CS1591
        OnrampPendingPlan,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampPlanning")]
        #pragma warning disable CS1591
        OnrampPlanning,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampPlanFailed")]
        #pragma warning disable CS1591
        OnrampPlanFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampPendingApproval")]
        #pragma warning disable CS1591
        OnrampPendingApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampPendingApply")]
        #pragma warning disable CS1591
        OnrampPendingApply,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampApplying")]
        #pragma warning disable CS1591
        OnrampApplying,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampApplyFailed")]
        #pragma warning disable CS1591
        OnrampApplyFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampActive")]
        #pragma warning disable CS1591
        OnrampActive,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampPendingDestroy")]
        #pragma warning disable CS1591
        OnrampPendingDestroy,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampDestroying")]
        #pragma warning disable CS1591
        OnrampDestroying,
        #pragma warning restore CS1591
        [EnumMember(Value = "OnrampDestroyFailed")]
        #pragma warning disable CS1591
        OnrampDestroyFailed,
        #pragma warning restore CS1591
    }
}
