// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Finished PKI rotation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Mconn_eventMember10_k
    {
        [EnumMember(Value = "FinishRotatePkiSuccess")]
        #pragma warning disable CS1591
        FinishRotatePkiSuccess,
        #pragma warning restore CS1591
    }
}
