// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Enum for access_application_policy resource type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Resource_tagging_zone_resource_type_access_application_policy_enum
    {
        [EnumMember(Value = "access_application_policy")]
        #pragma warning disable CS1591
        Access_application_policy,
        #pragma warning restore CS1591
    }
}
