// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember1"/>, <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkersAiPostRunCfGoogleGemma7bItLora : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember1? WorkersAiPostRunCfGoogleGemma7bItLoraMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember1 WorkersAiPostRunCfGoogleGemma7bItLoraMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember2? WorkersAiPostRunCfGoogleGemma7bItLoraMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember2 WorkersAiPostRunCfGoogleGemma7bItLoraMember2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLora"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLora CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLora();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkersAiPostRunCfGoogleGemma7bItLoraMember1 = new global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WorkersAiPostRunCfGoogleGemma7bItLoraMember2 = new global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(WorkersAiPostRunCfGoogleGemma7bItLoraMember1 != null)
            {
                return WorkersAiPostRunCfGoogleGemma7bItLoraMember1.GetFieldDeserializers();
            }
            else if(WorkersAiPostRunCfGoogleGemma7bItLoraMember2 != null)
            {
                return WorkersAiPostRunCfGoogleGemma7bItLoraMember2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(WorkersAiPostRunCfGoogleGemma7bItLoraMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember1>(null, WorkersAiPostRunCfGoogleGemma7bItLoraMember1);
            }
            else if(WorkersAiPostRunCfGoogleGemma7bItLoraMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.WorkersAiPostRunCfGoogleGemma7bItLoraMember2>(null, WorkersAiPostRunCfGoogleGemma7bItLoraMember2);
            }
        }
    }
}
#pragma warning restore CS0618
