// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Workers_observability_query_run_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "STARTED")]
        #pragma warning disable CS1591
        STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
    }
}
