// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Workers_ai_post_run_cf_nvidia_nemotron_3_120b_a12bMember2_messagesMember4_role
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "assistant")]
        #pragma warning disable CS1591
        Assistant,
        #pragma warning restore CS1591
    }
}
