// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>The type of operation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ZeroTrustGatewayOperation_operation_type
    {
        [EnumMember(Value = "create_list")]
        #pragma warning disable CS1591
        Create_list,
        #pragma warning restore CS1591
    }
}
