// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>The type of mitigation</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Abuse_reports_MitigationType
    {
        [EnumMember(Value = "legal_block")]
        #pragma warning disable CS1591
        Legal_block,
        #pragma warning restore CS1591
        [EnumMember(Value = "phishing_interstitial")]
        #pragma warning disable CS1591
        Phishing_interstitial,
        #pragma warning restore CS1591
        [EnumMember(Value = "network_block")]
        #pragma warning disable CS1591
        Network_block,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate_limit_cache")]
        #pragma warning disable CS1591
        Rate_limit_cache,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_suspend")]
        #pragma warning disable CS1591
        Account_suspend,
        #pragma warning restore CS1591
        [EnumMember(Value = "redirect_video_stream")]
        #pragma warning disable CS1591
        Redirect_video_stream,
        #pragma warning restore CS1591
    }
}
