// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Key Type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Api_shield_credentials_JWT_Key_EC_kty
    {
        [EnumMember(Value = "EC")]
        #pragma warning disable CS1591
        EC,
        #pragma warning restore CS1591
    }
}
