// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>ID of the zone setting.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CacheRules_variants_id
    {
        [EnumMember(Value = "variants")]
        #pragma warning disable CS1591
        Variants,
        #pragma warning restore CS1591
    }
}
