// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Dlp_SharedEntryUpdateMember3_entry_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "exact_data")]
        #pragma warning disable CS1591
        Exact_data,
        #pragma warning restore CS1591
    }
}
