// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmailSecurity_DispositionLabel_Value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MALICIOUS")]
        #pragma warning disable CS1591
        MALICIOUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MALICIOUS-BEC")]
        #pragma warning disable CS1591
        MALICIOUSBEC,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPICIOUS")]
        #pragma warning disable CS1591
        SUSPICIOUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPOOF")]
        #pragma warning disable CS1591
        SPOOF,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPAM")]
        #pragma warning disable CS1591
        SPAM,
        #pragma warning restore CS1591
        [EnumMember(Value = "BULK")]
        #pragma warning disable CS1591
        BULK,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENCRYPTED")]
        #pragma warning disable CS1591
        ENCRYPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXTERNAL")]
        #pragma warning disable CS1591
        EXTERNAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
    }
}
