// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_completed_bulk_operation"/>, <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_failed_bulk_operation"/>, <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_pending_or_running_bulk_operation"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Lists_operation : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_completed_bulk_operation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_completed_bulk_operation? ListsCompletedBulkOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_completed_bulk_operation ListsCompletedBulkOperation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_failed_bulk_operation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_failed_bulk_operation? ListsFailedBulkOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_failed_bulk_operation ListsFailedBulkOperation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_pending_or_running_bulk_operation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_pending_or_running_bulk_operation? ListsPendingOrRunningBulkOperation { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_pending_or_running_bulk_operation ListsPendingOrRunningBulkOperation { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_operation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_operation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_operation();
            if("lists_completed_bulk_operation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListsCompletedBulkOperation = new global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_completed_bulk_operation();
            }
            else if("lists_failed_bulk_operation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListsFailedBulkOperation = new global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_failed_bulk_operation();
            }
            else if("lists_pending_or_running_bulk_operation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ListsPendingOrRunningBulkOperation = new global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_pending_or_running_bulk_operation();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ListsCompletedBulkOperation != null)
            {
                return ListsCompletedBulkOperation.GetFieldDeserializers();
            }
            else if(ListsFailedBulkOperation != null)
            {
                return ListsFailedBulkOperation.GetFieldDeserializers();
            }
            else if(ListsPendingOrRunningBulkOperation != null)
            {
                return ListsPendingOrRunningBulkOperation.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(ListsCompletedBulkOperation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_completed_bulk_operation>(null, ListsCompletedBulkOperation);
            }
            else if(ListsFailedBulkOperation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_failed_bulk_operation>(null, ListsFailedBulkOperation);
            }
            else if(ListsPendingOrRunningBulkOperation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.Lists_pending_or_running_bulk_operation>(null, ListsPendingOrRunningBulkOperation);
            }
        }
    }
}
#pragma warning restore CS0618
