// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Type of source</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Mq_event_source_images_type
    {
        [EnumMember(Value = "images")]
        #pragma warning disable CS1591
        Images,
        #pragma warning restore CS1591
    }
}
