// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>What caused the deployment.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Pages_deployments_deployment_trigger_type
    {
        [EnumMember(Value = "push")]
        #pragma warning disable CS1591
        Push,
        #pragma warning restore CS1591
        [EnumMember(Value = "ad_hoc")]
        #pragma warning disable CS1591
        Ad_hoc,
        #pragma warning restore CS1591
    }
}
