// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>
    /// Configs for the project build process.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Pages_build_config : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enable build caching for the project.</summary>
        public bool? BuildCaching { get; set; }
        /// <summary>Command used to build project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildCommand { get; set; }
#nullable restore
#else
        public string BuildCommand { get; set; }
#endif
        /// <summary>Output directory of the build.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationDir { get; set; }
#nullable restore
#else
        public string DestinationDir { get; set; }
#endif
        /// <summary>Directory to run the command.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootDir { get; set; }
#nullable restore
#else
        public string RootDir { get; set; }
#endif
        /// <summary>The classifying tag for analytics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebAnalyticsTag { get; set; }
#nullable restore
#else
        public string WebAnalyticsTag { get; set; }
#endif
        /// <summary>The auth token for analytics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebAnalyticsToken { get; set; }
#nullable restore
#else
        public string WebAnalyticsToken { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Pages_build_config"/> and sets the default values.
        /// </summary>
        public Pages_build_config()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Pages_build_config"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.Pages_build_config CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.OpenApiClient.Models.Pages_build_config();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "build_caching", n => { BuildCaching = n.GetBoolValue(); } },
                { "build_command", n => { BuildCommand = n.GetStringValue(); } },
                { "destination_dir", n => { DestinationDir = n.GetStringValue(); } },
                { "root_dir", n => { RootDir = n.GetStringValue(); } },
                { "web_analytics_tag", n => { WebAnalyticsTag = n.GetStringValue(); } },
                { "web_analytics_token", n => { WebAnalyticsToken = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("build_caching", BuildCaching);
            writer.WriteStringValue("build_command", BuildCommand);
            writer.WriteStringValue("destination_dir", DestinationDir);
            writer.WriteStringValue("root_dir", RootDir);
            writer.WriteStringValue("web_analytics_tag", WebAnalyticsTag);
            writer.WriteStringValue("web_analytics_token", WebAnalyticsToken);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
