// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_aws"/>, <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_gcs"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class R2_put_bucket_sippy_config : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_aws"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_aws? R2EnableSippyAws { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_aws R2EnableSippyAws { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_gcs"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_gcs? R2EnableSippyGcs { get; set; }
#nullable restore
#else
        public global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_gcs R2EnableSippyGcs { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.R2_put_bucket_sippy_config"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Cloudflare.OpenApiClient.Models.R2_put_bucket_sippy_config CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Cloudflare.OpenApiClient.Models.R2_put_bucket_sippy_config();
            if("r2_enable_sippy_aws".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.R2EnableSippyAws = new global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_aws();
            }
            else if("r2_enable_sippy_gcs".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.R2EnableSippyGcs = new global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_gcs();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(R2EnableSippyAws != null)
            {
                return R2EnableSippyAws.GetFieldDeserializers();
            }
            else if(R2EnableSippyGcs != null)
            {
                return R2EnableSippyGcs.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(R2EnableSippyAws != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_aws>(null, R2EnableSippyAws);
            }
            else if(R2EnableSippyGcs != null)
            {
                writer.WriteObjectValue<global::Soenneker.Cloudflare.OpenApiClient.Models.R2_enable_sippy_gcs>(null, R2EnableSippyGcs);
            }
        }
    }
}
#pragma warning restore CS0618
