// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum R2_slurper_GCSSourceSchema_vendor
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gcs")]
        #pragma warning disable CS1591
        Gcs,
        #pragma warning restore CS1591
    }
}
