// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>The ranking type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Radar_get_ranking_domain_timeseries_Param_rankingType
    {
        [EnumMember(Value = "POPULAR")]
        #pragma warning disable CS1591
        POPULAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRENDING_RISE")]
        #pragma warning disable CS1591
        TRENDING_RISE,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRENDING_STEADY")]
        #pragma warning disable CS1591
        TRENDING_STEADY,
        #pragma warning restore CS1591
    }
}
