// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Target of CNAME record.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TlsCertificatesAndHostnames_verification_info_record_target
    {
        [EnumMember(Value = "record_value")]
        #pragma warning disable CS1591
        Record_value,
        #pragma warning restore CS1591
        [EnumMember(Value = "http_body")]
        #pragma warning disable CS1591
        Http_body,
        #pragma warning restore CS1591
        [EnumMember(Value = "cname_target")]
        #pragma warning disable CS1591
        Cname_target,
        #pragma warning restore CS1591
        [EnumMember(Value = "txt_value")]
        #pragma warning disable CS1591
        Txt_value,
        #pragma warning restore CS1591
    }
}
