// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Device resolutions.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Urlscanner_create_scan_bulk_v2_RequestBody_application_json_screenshotsResolutions
    {
        [EnumMember(Value = "desktop")]
        #pragma warning disable CS1591
        Desktop,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "tablet")]
        #pragma warning disable CS1591
        Tablet,
        #pragma warning restore CS1591
    }
}
