// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>The action to take when the expression matches.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Waitingroom_rule_action_Value
    {
        [EnumMember(Value = "bypass_waiting_room")]
        #pragma warning disable CS1591
        Bypass_waiting_room,
        #pragma warning restore CS1591
    }
}
