// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>If set, the types of subnets to include, separated by comma.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Zero_trust_networks_subnets_list_Param_subnet_types
    {
        [EnumMember(Value = "cloudflare_source")]
        #pragma warning disable CS1591
        Cloudflare_source,
        #pragma warning restore CS1591
        [EnumMember(Value = "warp")]
        #pragma warning disable CS1591
        Warp,
        #pragma warning restore CS1591
    }
}
