// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Indicate which version of the browser isolation controls should apply.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Zero_trust_gateway_rule_settings_biso_admin_controls_version
    {
        [EnumMember(Value = "v1")]
        #pragma warning disable CS1591
        V1,
        #pragma warning restore CS1591
        [EnumMember(Value = "v2")]
        #pragma warning disable CS1591
        V2,
        #pragma warning restore CS1591
    }
}
