// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Zone_cache_settings_change_origin_post_quantum_encryption_setting_RequestBody_application_json_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "preferred")]
        #pragma warning disable CS1591
        Preferred,
        #pragma warning restore CS1591
        [EnumMember(Value = "supported")]
        #pragma warning disable CS1591
        Supported,
        #pragma warning restore CS1591
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
    }
}
