// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>
    /// HTTP/2 Edge Prioritization optimises the delivery of resources served through HTTP/2 to improve page load performance. It also supports fine control of content delivery when used in conjunction with Workers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Zones_h2_prioritization : global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_base, IParsable
    {
        /// <summary>Strongly‐typed enum value</summary>
        public new Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization_value? Value { get; set; } = global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization_value.Off;

        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization"/> and sets the default values.
        /// </summary>
        public Zones_h2_prioritization() : base()
        {
            Value = global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization_value.Off;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            var map = new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers());
            map["value"] = n => { Value = n.GetEnumValue<Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization_value>(); };
            return map;
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<Soenneker.Cloudflare.OpenApiClient.Models.Zones_h2_prioritization_value>("value", Value);
        }
    }
}
#pragma warning restore CS0618
