// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Cloudflare.OpenApiClient.Models
{
    /// <summary>Value of the zone setting.Notes: Default value depends on the zone&apos;s plan level.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Zones_automatic_https_rewrites_value_Value
    {
        [EnumMember(Value = "on")]
        #pragma warning disable CS1591
        On,
        #pragma warning restore CS1591
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
    }
}
